version: "3"
services:
  pdf_generator_server:
    build: ./pdf_generator_server
    command: npm start
    ports:
      - "3000:3000"
    networks:
      - app-network
  real_assist_client:
    build: ./real_assist_client
    command: npm run dev
    ports:
      - "5173:5173"
    networks:
      - app-network
networks:
  app-network: